service: line-slideshow-frontend
frameworkVersion: '3'
provider:
  name: aws
  stage: dev
  region: ap-northeast-1
  runtime: nodejs20.x
  environment:
    NUXT_PUBLIC_ENV: dev
package:
  patterns:
    - '!**'
    - .output/**
functions:
  NuxtSsrEngine:
    handler: .output/server/index.handler
    url: true